---
collections:
  - name: theforeman.foreman
    source: https://galaxy.ansible.com

#  - name: redhat.satellite
#    source: https://cloud.redhat.com/api/automation-hub/

roles:
  - name: redhat_sap.sap_rhsm
  - name: redhat_sap.sap_hostagent
  - name: redhat_sap.sap_hana_deployment
  - name: redhat_sap.sap_s4hana_deployment