- name: deploy vms via satellite
  hosts: localhost
  gather_facts: no
  collections:
    -  theforeman.foreman
  vars:
    sat_image_name: HANA_Image
    vm_name: lab1test01
    sat_host_group: HANA_Image
    domain_name: example.com

  tasks:
    - name: get all environment vars
      command: printenv
      register: get_env_vars

    - debug:
        msg: "{{ get_env_vars }}"

    - name: create host via satellite
      host:
#        server_url: "{{ lookup('env', 'FOREMAN_SERVER') }}"
#        username: "{{ lookup('env', 'FOREMAN_USER') }}"
#        password: "{{ lookup('env', 'FOREMAN_PASSWORD') }}"
        name: "{{ vm_name }}.{{ domain_name }}"
        hostgroup: "{{ sat_host_group }}"
        location: Chattanooga
        organization: Shadow Man
#        operatingsystem: RHEL 8.1
#        build: true
#        provision_method: image
#        image: "{{ sat_image_name }}"
        state: present