- name: deploy vms via satellite
  hosts: localhost
  gather_facts: no
  collections:
    -  redhat.satellite
  vars:
    sat_image_name: HANA_Image
    vm_name: lab1test01
    sat_host_group: HANA_Image
    domain_name: example.com

  tasks:
    - name: create host via satellite
      host:
        server_url: "{{ lookup('env', 'FOREMAN_SERVER') }}"
        username: "{{ lookup('env', 'FOREMAN_USER') }}"
        password: "{{ lookup('env', 'FOREMAN_PASSWORD') }}"
        name: "{{ vm_name }}.{{ domain_name }}"
        hostgroup: "{{ sat_host_group }}"
        build: true
        provision_method: image
        image: "{{ sat_image_name }}"
        state: present