- name: deploy vms via satellite
  hosts: localhost
  gather_facts: no
  collections:
    -  theforeman.foreman
  vars:
    sat_image_name: HANA_Image
    vm_name: lab1test01
    sat_host_group: HANA_Image
    domain_name: example.com

  tasks:
#    - name: create host via satellite
#      host:
#        server_url: "{{ lookup('env', 'FOREMAN_SERVER') }}"
#        username: "{{ lookup('env', 'FOREMAN_USER') }}"
#        password: "{{ lookup('env', 'FOREMAN_PASSWORD') }}"
#        name: "{{ vm_name }}.{{ domain_name }}"
#        hostgroup: "{{ sat_host_group }}"
#        location: Chattanooga
#        organization: Shadow Man
#        operatingsystem: "RHEL 8.1"
#        provision_method: image
#        image: "{{ sat_image_name }}"
#        state: present

    - name: create vm via satellite
      uri:
        url: "{{ lookup('env', 'FOREMAN_SERVER') }}/api/v2/hosts"
        user: "{{ lookup('env', 'FOREMAN_USER') }}"
        password: "{{ lookup('env', 'FOREMAN_PASSWORD') }}"
        validate_certs: false
        force_basic_auth: true
        timeout: 14400
        method: POST
        body_format: json
        body:
          host:
            name: "{{ vm_name }}.{{ domain_name }}"
            operatingsystem_id: "{{ operatingsystem_id | default('2') }}"
            managed: true
            provision_method: image
            image_id: "{{ image_id | default('10') }}"
            hostgroup_id: "{{ hostgroup_id | default('16') }}"
            location_id: "{{ location_id | default('2') }}"
            organization_id: "{{ organization_id | default('1') }}"
            interfaces_attributes:
              name: "{{ vm_name }}"
      register: deploy_status
#      changed_when:
#        - deploy_status.status | int == 201
#      failed_when:
#        - deploy_status.status | int != 201
#        - deploy_status.json.error.full_messages is defined
#        - "'Name has already been taken' not in deploy_status.json.error.full_messages"