---

- name: Set up VM
  hosts: lab1*
#  serial: 1

  tasks:
  - name: Set Hostname on "{{ name }}"
    hostname:
      name: "{{ name }}"

  - name: Subscribe to our Satellite using our activation key
    redhat_subscription:
      state: present
      activationkey: SAP HANA Server
      org_id: Shadow_Man
    failed_when: false

  - name: Reboot the machine
    reboot: