---

- name: Set up VM
  hosts: "{{ vm_prefix }}*"
  vars:
    software_repo_nfs_server: localhost
    software_repo_path: /var/lib/exports/software
    local_repo_path: /software

  tasks:
    - name: Subscribe to our Satellite using our activation key
      redhat_subscription:
        state: present
        activationkey: SAP HANA Server
        org_id: Shadow_Man
        auto_attach: yes
      failed_when: false

    - name: build hosts file
      lineinfile:
        dest: /etc/hosts
        regexp: '.*{{ item }}$'
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_fqdn }} {{ hostvars[item].ansible_hostname }}"
        state: present
      when: hostvars[item].ansible_default_ipv4.address is defined
      loop: "{{ play_hosts }}"

    - name: ensure software repo directory exists
      file:
        path: "{{ local_repo_path }}"
        state: directory

    - name: ensure nfs utils are present
      package:
        name:
          - nfs-utils
          - nfs4-acl-tools

    - name: ensure software repo is mounted
      mount:
        path: "{{ local_repo_path }}"
        src: "{{ software_repo_nfs_server }}:/{{ software_repo_path }}"
        fstype: nfs
        opts: ro,_netdev
        state: mounted