---

- name: Set up VM
  hosts: "{{ vm_prefix }}"

  tasks:
  - name: Subscribe to our Satellite using our activation key
    redhat_subscription:
      state: present
      activationkey: SAP HANA Server
      org_id: Shadow_Man
    failed_when: false