- name: remove vms via satellite
  hosts: all
  gather_facts: no

  tasks:

    - name: delete vm via satellite
      uri:
        url: "{{ lookup('env', 'FOREMAN_SERVER') }}/api/v2/hosts/{{ foreman.id | default(sat_host_id) }}"
        user: "{{ lookup('env', 'FOREMAN_USER') }}"
        password: "{{ lookup('env', 'FOREMAN_PASSWORD') }}"
        validate_certs: false
        force_basic_auth: true
        timeout: 14400
        method: DELETE
        body_format: json
        body:
          host:
            id: "{{ foreman.id }}"
            location_id: "{{ location_id | default('2') }}"
            organization_id: "{{ organization_id | default('1') }}"
      register: deploy_status
      when: foreman.id | default(sat_host_id) | default(None) is defined
      delegate_to: localhost


    # let's wait for a bit for removal to finish, should improve this later
    - pause:
        seconds: 30