---

- hosts: all
  roles:
    - { role: redhat_sap.sap_rhsm }
    - { role: redhat_sap.sap_hostagent }

- hosts: *02
  roles:
    - { role: redhat_sap.sap_hana_deployment }

- hosts: *01
  roles:
    - { role: redhat_sap.sap_s4hana_deployment }