---

- hosts: "{{ vm_prefix }}*"
  roles:
    - redhat_sap.sap_rhsm
    - redhat_sap.sap_hostagent

- hosts: "{{ vm_prefix }}02,{{ vm_prefix }}03"
  roles:
    - sap-hana-preconfigure
    - redhat_sap.sap_hana_deployment

- hosts: "{{ vm_prefix }}01"
  roles:
    - redhat_sap.sap_s4hana_deployment