---

- hosts: "{{ vm_prefix }}*"
  roles:
    - redhat_sap.sap_rhsm
    - redhat_sap.sap_hostagent

- hosts: "{{ vm_prefix }}*:&*hana_image"
  roles:
    - sap-hana-preconfigure
    - redhat_sap.sap_hana_deployment

- hosts: "{{ vm_prefix }}*:&*s4_image"
  roles:
    - redhat_sap.sap_s4hana_deployment