---

- hosts: lab1*
  roles:
    - { role: redhat_sap.sap_rhsm }
    - { role: redhat_sap.sap_hostagent }

- hosts: lab1*02
  roles:
    - { role: redhat_sap.sap_hana_deployment }

- hosts: lab1*01
  roles:
    - { role: redhat_sap.sap_s4hana_deployment }