- name: wait for ip to be available
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_names: "{{ vm_name.split(',') | default([]) }}"

  tasks:
    - block:
        - name: obtain SSO token with using username/password credentials
          ovirt_auth:
            url: "{{ lookup('env', 'OVIRT_URL')|default(ovirt.url) }}"
            username: "{{ lookup('env', 'OVIRT_USERNAME')|default(ovirt.username) }}"
            password: "{{ lookup('env', 'OVIRT_PASSWORD')|default(ovirt.password) }}"
            insecure: yes

        - name: Check if VM has agent installed for Linux
          ovirt_vm_info:
            auth: "{{ ovirt_auth }}"
            pattern: name={{ item }}
          register: result
          until: result.ovirt_vms[0].guest_operating_system.kernel.version.build | default(None) != None
          failed_when: result.ovirt_vms | length == 0
          retries: 60
          delay: 10
          loop: "{{ vm_names }}"

      always:
        - name: revoke the SSO token
          ovirt_auth:
            url: "{{ lookup('env', 'OVIRT_URL')|default(ovirt.url) }}"
            username: "{{ lookup('env', 'OVIRT_USERNAME')|default(ovirt.username) }}"
            password: "{{ lookup('env', 'OVIRT_PASSWORD')|default(ovirt.password) }}"
            insecure: yes
            ovirt_auth: "{{ ovirt_auth }}"
            state: absent