---
roles:
  - name: redhat_sap.sap_rhsm
    src: https://github.com/redhat-sap/sap-rhsm.git
  - name: redhat_sap.sap_hostagent
    src: https://github.com/redhat-sap/sap_hostagent.git
  - name: redhat_sap.sap_hana_deployment
    src: https://github.com/redhat-sap/sap_hana_deployment.git
  - name: redhat_sap.sap_s4hana_deployment
    src: https://github.com/redhat-sap/sap_s4hana_deployment.git