---
roles:
  - name: redhat_sap.sap_rhsm
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_hostagent
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_hana_deployment
    source: https://galaxy.ansible.com
  - name: redhat_sap.sap_s4hana_deployment
    source: https://galaxy.ansible.com